package com.example

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val summary: String,
    val report: String,
    val totalBalance: String,
    val costs: String,
    val remaining: String,
    val of: String,
    val searchExpenses: String,
    val quickAdd: String,
    val noExpenses: String,
    val total: String,
    val selectTheme: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val selectLanguage: String,
    val close: String,
    val warningLimit: String,
    val warningLimit100: String,
    val addExpense: String,
    val editBudget: String,
    val name: String,
    val amount: String,
    val category: String,
    val save: String,
    val add: String,
    val cancel: String,
    val settings: String,
    val shareReport: String,
    val qGroceries: String,
    val qTransport: String,
    val qRent: String,
    val qCoffee: String,
    val qMovies: String,
    val catFood: String,
    val catTransport: String,
    val catHousing: String,
    val catEntertainment: String,
    val catUtilities: String,
    val catOther: String
)

val EnStrings = AppStrings(
    summary = "SUMMARY",
    report = "REPORT",
    totalBalance = "TOTAL BALANCE",
    costs = "COSTS",
    remaining = "REMAINING",
    of = "of ",
    searchExpenses = "Search expenses...",
    quickAdd = "QUICK ADD",
    noExpenses = "No Expenses",
    total = "TOTAL",
    selectTheme = "Select Theme",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    selectLanguage = "Select Language",
    close = "Close",
    warningLimit = "You have spent over 80% of your monthly budget!",
    warningLimit100 = "You have reached 100% of your monthly budget!",
    addExpense = "Add Expense",
    editBudget = "Edit Budget",
    name = "Name",
    amount = "Amount",
    category = "Category",
    save = "Save",
    add = "Add",
    cancel = "Cancel",
    settings = "Settings",
    shareReport = "Share Report",
    qGroceries = "Groceries",
    qTransport = "Transport",
    qRent = "Rent",
    qCoffee = "Coffee",
    qMovies = "Movies",
    catFood = "Food",
    catTransport = "Transport",
    catHousing = "Housing",
    catEntertainment = "Entertainment",
    catUtilities = "Utilities",
    catOther = "Other"
)

val RuStrings = AppStrings(
    summary = "СВОДКА",
    report = "ОТЧЕТ",
    totalBalance = "ОБЩИЙ БАЛАНС",
    costs = "РАСХОДЫ",
    remaining = "ОСТАТОК",
    of = "из ",
    searchExpenses = "Поиск расходов...",
    quickAdd = "БЫСТРОЕ ДОБАВЛЕНИЕ",
    noExpenses = "Нет расходов",
    total = "ИТОГО",
    selectTheme = "Выбор темы",
    themeSystem = "Системная",
    themeLight = "Светлая",
    themeDark = "Темная",
    selectLanguage = "Выбор языка",
    close = "Закрыть",
    warningLimit = "Вы потратили более 80% месячного бюджета!",
    warningLimit100 = "Вы исчерпали 100% месячного бюджета!",
    addExpense = "Добавить расход",
    editBudget = "Изменить бюджет",
    name = "Название",
    amount = "Сумма",
    category = "Категория",
    save = "Сохранить",
    add = "Добавить",
    cancel = "Отмена",
    settings = "Настройки",
    shareReport = "Поделиться отчетом",
    qGroceries = "Продукты",
    qTransport = "Транспорт",
    qRent = "Аренда",
    qCoffee = "Кофе",
    qMovies = "Кино",
    catFood = "Еда",
    catTransport = "Транспорт",
    catHousing = "Жилье",
    catEntertainment = "Развлечения",
    catUtilities = "Коммуналка",
    catOther = "Другое"
)

val UkStrings = AppStrings(
    summary = "ЗВЕДЕННЯ",
    report = "ЗВІТ",
    totalBalance = "ЗАГАЛЬНИЙ БАЛАНС",
    costs = "ВИТРАТИ",
    remaining = "ЗАЛИШОК",
    of = "з ",
    searchExpenses = "Пошук витрат...",
    quickAdd = "ШВИДКЕ ДОДАВАННЯ",
    noExpenses = "Немає витрат",
    total = "РАЗОМ",
    selectTheme = "Вибір теми",
    themeSystem = "Системна",
    themeLight = "Світла",
    themeDark = "Темна",
    selectLanguage = "Вибір мови",
    close = "Закрити",
    warningLimit = "Ви витратили понад 80% місячного бюджету!",
    warningLimit100 = "Ви вичерпали 100% місячного бюджету!",
    addExpense = "Додати витрату",
    editBudget = "Змінити бюджет",
    name = "Назва",
    amount = "Сума",
    category = "Категорія",
    save = "Зберегти",
    add = "Додати",
    cancel = "Скасувати",
    settings = "Налаштування",
    shareReport = "Поділитися звітом",
    qGroceries = "Продукти",
    qTransport = "Транспорт",
    qRent = "Оренда",
    qCoffee = "Кава",
    qMovies = "Кіно",
    catFood = "Їжа",
    catTransport = "Транспорт",
    catHousing = "Житло",
    catEntertainment = "Розваги",
    catUtilities = "Комуналка",
    catOther = "Інше"
)

val LocalAppStrings = staticCompositionLocalOf { EnStrings }
